name: Run ClearML Task

on:
  pull_request:
    branches: [main]

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    env:  # ✅ env:  # Global environment variables for all steps
      CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.API_HOST }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug ENV
        run: |
          echo "API_HOST=$API_HOST"
          if [ -z "$API_HOST" ]; then echo "❌ HOST is empty!"; exit 1; fi
          curl -I $API_HOST

      - name: Run pipeline
        run: |
#          clearml-agent daemon --queue "task" --detached
#          python main.py
          python s1_dataset_artifact.py

          
