name: CI + ClearML Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code:
    name: Code Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r MLOPS_Pipeline/requirements.txt
          pip install flake8

      - name: Run flake8 (optional linting)
        run: flake8 MLOPS_Pipeline/ --ignore=E501 || true

  run-clearml-pipeline:
    name: Trigger ClearML Pipeline
    needs: check-code
    runs-on: ubuntu-latest

    env:
      CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      CLEARML_API_HOST: ${{ secrets.API_HOST }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ClearML
        run: pip install clearml

      - name: Trigger pipeline via controller
        run: python pipeline_controller.py
